### ISSUE TITLE
Clarify sounds license

### ISSUE THREAD

**Issue by mk-pmb** [surikov/webaudiofontdata#1]
Hi, thanks for your WebAudioFont project, and this data for it!
The license file makes it look like you publish this entire repo under MIT license. Could you clarify whether that extends to the actual sound data, and how you obtained effective permission to publish the sound data under MIT license? Lots of sound filenames here look like they're ports of proprietary tunes so it's important to know how free they really are.

Update: I found some batch files which look like the sound data might not be vendor's original wavetables, but rather auto-generated music of your own. If so, could you write that in the readme?
Could you maybe even point out which programs you used to generate the sound fonts, so people can make audiofonts files from their own wavetables?

Update 2: Then again, those `.sf2` file look like they might need license clarification.

**Comment by surikov** [comment]
look to original SF2 files
https://github.com/surikov/webaudiofontdata/tree/master/sf2

I don't know what license they should use.

**Comment by mk-pmb** [comment]
That's a bummer. Unfortunately in my country that means I cannot safely use them. :-(
So what about the DIY approach? If I were to obtain some sf2 wavetables with a good license, how could I convert them?

**Comment by surikov** [comment]
Use instruments with "GeneralUserGS" in names. They converted from 
http://schristiancollins.com/generaluser.php
see license for this lib at
https://github.com/surikov/webaudiofontdata/blob/master/sf2/GeneralUserGS_LICENSE.txt

You can send me any .sf2 you need. I will place it to the webaudiofontdata library.

**Comment by mk-pmb** [comment]
> You can send me any .sf2 you need. I will place it to the webaudiofontdata library.

Thanks! I'll take that up if I find a special wavetable that I like. For now I'll try make do with the [midi-js-soundfonts](https://github.com/gleitz/midi-js-soundfonts) – just found them a few minutes ago, they're under Creative Commons license.

**Comment by surikov** [comment]
midi.js doesn't support sampleloops. It doesn't have nor equalizer, nor reverberation, nor compressor. It uses Fluid soundfont that inappropriate for webapps due of huge size.

this is why i created webaudiofont.

**Comment by mk-pmb** [comment]
Would Fluid's size problem be solved by converting it to a webaudiofont, because each instrument is split into its own file? If so, could you please add [the debian fluid-soundfont-gm](http://pimpmybyte.de/ftp-area/mirror/debian-unpacked/fluid-soundfont-gm/FluidR3_GM.sf2)?

**Comment by surikov** [comment]
Why do you need a soundfont that doesn't support sampleloops?

Try to probe existed sounfonts first.

**Comment by mk-pmb** [comment]
There are very good soundfonts here already, in terms of sound. However, I want to use them in free software projects hosted in Germany, so I need soundfonts for which I can get reliable, effective permission to re-publish them.

In the meantime I found another, smaller (6 MB) soundfont: [debian's timgm6mb](http://pimpmybyte.de/ftp-area/mirror/debian-unpacked/timgm6mb-soundfont/timgm6mb.zip).
That one is [licensed as GPL v2](http://pimpmybyte.de/ftp-area/mirror/debian-unpacked/timgm6mb-soundfont/copyright.txt) so if you lived here, you'd have to adapt your repo's license file. I russia though, probably nobody cares. :-)

__Update:__ I've read the GeneralUser GS license, even before opening this thread. In it, the author admits that he cannot guarantee he holds copyright for all the data in the file. Under German law, he is therefor not able to grant me permission to use them freely and re-publish them. Even his attempt to do so is limited to "for your own music creation", a much lesser range of usage than usual free software offers.

**Comment by surikov** [comment]
Read again

Use instruments with "GeneralUserGS" in names. They converted from
http://schristiancollins.com/generaluser.php
see license for this lib at
https://github.com/surikov/webaudiofontdata/blob/master/sf2/GeneralUserGS_LICENSE.txt

This is answer to your issue.

Open other issue about russia if you wish. 
This issue is closed.

**Comment by mk-pmb** [comment]
Thanks. I've read the GeneralUser GS license. In it, the author admits that he cannot guarantee he holds copyright for all the data in the file. Under German law, he is therefor not able to grant me permission to use them freely and re-publish them. Even his attempt to do so is limited to "for your own music creation", a much lesser range of usage than usual free software offers.

**Comment by mk-pmb** [comment]
Since the discussion started again in https://github.com/nfroidure/MIDIFile/issues/27 seems to be longer, let's continue here, as this isn't really about MIDIfile.

Quick recap for other readers:

@surikov wrote:
> You didn't read my answer.
> I posted links to license of used soundfonts.

I wrote:
> I read your answer and I read the licenses. However, we seem to have different interpretation of European law and thus, different opinions about its legal consequences.

@surikov wrote:
> read https://github.com/surikov/webaudiofont/blob/master/LICENSE.md
> Thousands of projects from Europe use this license.

Your MIT license file is what I meant with "clain to be FOSS". That claim is a very good start, thus my thumbs up emoji, over in the MIDIfile issue thread.
On a minor note, the claim would be more helpful if you add your name in the copyright line.

In the first paragraph of the license, you attempt to grant me certain permissions. If someone tries to sue me for re-distributing that audio data, a court would have to check whether your attempt was successful. The court would therefor have to check whether it believes you yourself have enough permissions to grant said permissions, according to European law. (Because usually the courts check the law of the region of the persons being sued, not caring about which law would have applied to someone else somewhere on the internet.)

So as long as I cannot see a way to prove to a European court that you have sufficient permission to grant the license __in Europe__, your license is useless to me.

__Update:__ Sorry, I now discovered that you meant the MIT license applying to the other repo without the sound files. It may be effective there, but without the audio data, it's still useless.

**Comment by surikov** [comment]
This is standard MIT license. Of Course you can't use this project if you can't use MIT license.
Project uses free soundfonts from some Linux distributions. Many users from Europe uses Linux.

**Comment by mk-pmb** [comment]
With the MIT license you try to grant me some permissions. In european law, this only works if you had a permission to grant the permission. If we ignore that cars cannot easily be copied, it's a bit like a car use license. If I want to use some car, it's nice to have your permission to use it. However, I also have to trust that you have enough permission. You'll say "of course it's my car I am the owner I can allow you to use it." However, if it turns out the shop where you bought the car was tricked by a thief, then the permission I have from you isn't enough.

As a more direct example, let's say I want to use a GeneralUser GS sound font. In the MIT license you claim to give me permission

> "to deal in the Software without restriction"

– how can I prove to a European court that you are allowed to give that permission? The original author states in the GeneralUser GS license file:

> of the samples […] some were taken from other banks freely (and legally) available on the Internet from various SoundFont websites.

The problem with this is that he seems to be an American citizen, so whatever counts as "freely and legally" to him doesn't mean it's legal in Europe, e.g. if he used public domain data that has different copyright expiration dates in US and EU. I'd have to prove the entire chain of copyright from him to you and then to me.

You can observe similar problems with books. Project Gutenberg has scanned lots of old books that became Public Domain in the US. Then someone in a somewhat-crazy EU state tried to sue them, partially successful, because copyright for some of those books might still be valid in the EU. So even if Project Gutenberg grants me permission to do whatever with the books, their permission is useless for me.

Free software licenses aren't as easy as it might seem at first.

**Comment by surikov** [comment]
Sorry, I can't help You with European court.
Find any Linux user and ask him about Your problem.
You can't use this project if You can't use MIT license.

**Comment by mk-pmb** [comment]
Thanks for taking up my suggestion from 2017-08-20 of using Debian's Fluid R3 soundfont again. In your `sf2` folder, the `_FluidDrums.bat` and `_FluidPitch.bat` look like you were using a sf2 source file. However, the Fluid R3 license link in your readme points to a directory with only an sf3 file.

So, could you clarify (ideally in the readme) which file you have generated the Fluid soundfont from, and which license came with it?

In case you're not sure, could you…
* get the official Debian version (official links: [info page](https://packages.debian.org/stable/sound/fluid-soundfont-gm), [license](http://metadata.ftp-master.debian.org/changelogs/main/f/fluid-soundfont/fluid-soundfont_3.1-5.1_copyright), [download](http://http.debian.net/debian/pool/main/f/fluid-soundfont/fluid-soundfont_3.1.orig.tar.gz)),
* convert that one,
* write in your Readme that you obtained it from Debian,
* and include their license file somewhere in your repo?

**Comment by surikov** [comment]
No. This is my own library not Debian one.
Yes, I used well known opensource Fluid soundfont to create my own library.
WebAudioFont has MIT license. It is enough for any projects.

**Comment by mk-pmb** [comment]
> No. This is my own library not Debian one.

I didn't mean to replace your library's license. I meant to add the original Fluid license file to this data repo, in a way that makes clear it's the license you used to obtain your version of the Fluid soundfont.
Like in the MuseScore project to which your readme had the link. They have their project license (GPL) in [their main directory](https://github.com/musescore/MuseScore/) and also their Fluid license in [subdirectory share/sound](https://github.com/musescore/MuseScore/tree/master/share/sound).

**Comment by surikov** [comment]
Read again. This is same file.
This is my own library. This library MIT license.

No need to change anything.

**Comment by mk-pmb** [comment]
Sorry if I seem dumb. Which files are the same ones? Is the file you used the .sf3 from the MuseScore repo?

At least the MuseScore file is not the same as from Debian, they have different SHA1 checksums:
```text
ddc6dfe2c7e0fc58712f5b1002eb8f39a9073b01  FluidR3Mono_GM.sf3---from-MuseScore
4fd467afcb45c8b4cfd1eadac9372a819e35d46d  FluidR3_GM.sf2---from-Debian
```

**Comment by surikov** [comment]
> and also their Fluid license in subdirectory share/sound

Link from Musescore subdirectory and link from WebAudioFontData project points to same file with Fluid license.

BTW
WebAudioFont isn't Fluid. WebAudioFont doesn't share files from Fluid projects. You don't need to ask about Fluid license. I used sounds (not files) from some soundfonts and made my own code that I share under MIT license.

MIT license enough for any project. If you can't use MIT license you can't use WebAudioFont. Create your own implementation of audio engine, instruments, drums, etc. and use it.

**Comment by mk-pmb** [comment]
> I used sounds (not files) from some soundfonts and made my own code that I share under MIT license.

Sounds like we had a HUGE misunderstanding in the very first posts in this thread, where I guessed:

> the sound data might not be […], but rather auto-generated music of your own.

… I think the "auto-generated" might have been misleading.

As I understand now, the soundfonts in your repo contain only music that you created yourself?
In that case, it would help a lot if you write that in your readme, like
"All sound data in this project is from music that I created myself. They are NOT adaptations or translations of existing wavetable files."

**Comment by mk-pmb** [comment]
> WebAudioFont doesn't share files from Fluid projects. You don't need to ask about Fluid license.

Maybe I should also explain why it's relevant.
In many parts of the world, copyright not only applies to the files themselves but also the data inside them. If you just translate the data into another language or format, that doesn't make you the creator. If the translation is done by a program (without creative input from a human), it's even more clear that no new creation (as in creativity) has occurred. Afaik this interpretation applies at least in USA and Europe.
