### ISSUE TITLE
SF2 -> .js Generator

### ISSUE THREAD

**Issue by clee-ai** [surikov/webaudiofontdata#2]
Hi,

Thank you for this. I was wondering if it would be possible to share the generator you use for transforming the SF2 files into JS files so that I can use my own sountfonts.

Thanks!

**Comment by surikov** [comment]
Search GitHub. There are many sf2 readers.
Upload your soundfont here if you need it in WebAudioFontData.

PS
I looked to your melodymeasures.com. ou use patch files from Gravis Ultrasound soundcards. I bought GUS for my first PS about of 25 years ago 8)
