### ISSUE TITLE
Can you add my files to webaudiofontdata

### ISSUE THREAD

**Issue by bbevren** [surikov/webaudiofontdata#3]
I have tried to add it to local but no success...could you add them to your library? These are ethnic instruments from middle-east. 10 instruments created locally. Thanks for great library. All instruments has sf2 format. I could not convert them to js

**Comment by surikov** [comment]
Look to tutorial for custom samples
https://surikov.github.io/webaudiofont/#custom-samples

This is hard work. I haven't enough time to convert your samples for you.
You need to do this yourself.
